import * as FileSystem from 'expo-file-system/legacy';
import * as Sharing from 'expo-sharing';
import * as Print from 'expo-print';

export class ExportService {
  static async exportToCSV(data: any[], filename: string) {
    if (data.length === 0) return;

    // Generate CSV Header
    const headers = Object.keys(data[0]).join(',');
    const rows = data.map(obj => 
      Object.values(obj).map(val => `"${val}"`).join(',')
    ).join('\n');

    const csvContent = `${headers}\n${rows}`;
    const fileUri = `${FileSystem.documentDirectory}${filename}.csv`;

    await FileSystem.writeAsStringAsync(fileUri, csvContent, {
      encoding: 'utf8',
    });

    await Sharing.shareAsync(fileUri);
  }

  static async exportToPDF(html: string, filename: string) {
    const { uri } = await Print.printToFileAsync({ html });
    const fileUri = `${FileSystem.documentDirectory}${filename}.pdf`;

    await FileSystem.moveAsync({
      from: uri,
      to: fileUri,
    });

    await Sharing.shareAsync(fileUri);
  }

  static generateReceiptHTML(scan: any) {
    const itemsRows = scan.items.map((item: any) => `
      <tr>
        <td style="padding: 10px; border-bottom: 1px solid #eee;">${item.cleanName || item.shorthand}</td>
        <td style="padding: 10px; border-bottom: 1px solid #eee; text-align: right;">₹${item.price.toFixed(2)}</td>
      </tr>
    `).join('');

    return `
      <html>
        <body style="font-family: sans-serif; padding: 40px; color: #333;">
          <h1 style="color: #6366f1;">VisionBill Receipt</h1>
          <p><strong>ID:</strong> ${scan._id}</p>
          <p><strong>Date:</strong> ${new Date(scan.createdAt).toLocaleDateString()}</p>
          <hr style="border: 0; border-top: 2px solid #6366f1; margin: 20px 0;">
          <table style="width: 100%; border-collapse: collapse;">
            <thead>
              <tr style="background: #f8fafc;">
                <th style="padding: 10px; text-align: left; border-bottom: 2px solid #ddd;">Item</th>
                <th style="padding: 10px; text-align: right; border-bottom: 2px solid #ddd;">Price</th>
              </tr>
            </thead>
            <tbody>
              ${itemsRows}
            </tbody>
            <tfoot>
              <tr>
                <td style="padding: 20px 10px; font-weight: bold;">Grand Total</td>
                <td style="padding: 20px 10px; text-align: right; font-weight: bold; font-size: 20px; color: #6366f1;">₹${scan.extractedTotal.toFixed(2)}</td>
              </tr>
            </tfoot>
          </table>
          <footer style="margin-top: 60px; text-align: center; color: #94a3b8; font-size: 12px;">
            Generated by VisionBill - Your Premium Shopping Companion
          </footer>
        </body>
      </html>
    `;
  }
}
